title: Sumer Vaid
description: >- # this means to ignore newlines until "baseurl:"
  Personal academic website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sumervaid.github.io" # GitHub Pages URL

# Build settings
theme: jekyll-theme-primer
primer:
  color_scheme: dark

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true
      share: true
      related: true

# Site Author
author:
  name: "Sumer Vaid"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Your bio here"
  location: "Your Location"
  email: "your.email@example.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sumervaid"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourusername"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/yourusername"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sumervaid"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourusername"

# Reading Files
include:
  - _pages
  - _posts
  - _drafts
  - _data
  - _assets 